LOCAL_SOURCES= Cipher.cpp Mac.cpp Base.cpp

$(P).o: $(LOCAL_SOURCES)
	$(CC) $(CFLAGS) -c $(LOCAL_SOURCES)

$(PD).o: $(LOCAL_SOURCES)
	$(CC) $(DFLAGS) -c $(LOCAL_SOURCES)

$(T).o: $(LOCAL_SOURCES)
	$(CC) $(DFLAGS) -c $(LOCAL_SOURCES)
